# Generated by Django 3.0.3 on 2020-03-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaketTerapi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga', models.IntegerField()),
                ('aktif', models.BooleanField()),
                ('publikasi', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paket_terapi',
            },
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.DateTimeField(auto_now_add=True)),
                ('bayar', models.DateTimeField()),
                ('mulai', models.DateTimeField()),
                ('akhir', models.DateTimeField()),
                ('setujui', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pesanan',
            },
        ),
    ]
