# Generated by Django 3.0.3 on 2020-03-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypno', '0002_auto_20200306_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketterapi',
            name='akhir',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paketterapi',
            name='mulai',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
