# Generated by Django 3.0.3 on 2020-03-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypno', '0003_auto_20200306_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paketterapi',
            name='akhir',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paketterapi',
            name='mulai',
            field=models.DateField(),
        ),
    ]
