# Generated by Django 3.0.3 on 2020-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypno', '0004_auto_20200306_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='keterangan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
