# Generated by Django 3.0.3 on 2020-03-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypno', '0005_auto_20200311_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='path',
        ),
        migrations.AddField(
            model_name='audio',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
