# Generated by Django 3.0.3 on 2020-03-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypno', '0006_auto_20200311_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='filename',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(null=True, upload_to='./hypno/static/audio/'),
        ),
    ]
