# Generated by Django 3.0.3 on 2020-04-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypno', '0008_auto_20200314_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='paketterapi',
            name='ikon_src',
            field=models.TextField(null=True),
        ),
    ]
