"""
Django settings for hypnoAppStaff project.

Generated by 'django-admin startproject' using Django 2.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u8+t-&nyo*22evn29c4ovq8oe&$yko@t#goc_$sy#m2hl3!u@d'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '101.50.1.185']
ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
    'akun',
    'artikel',
    'hypno',
    'login',
    'order',
    'beranda',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'hypnoAppStaff.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hypnoAppStaff.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'hypno.db'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    # '.','static',
    os.path.join(BASE_DIR, 'static')
]
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Settings for sending email
# DEFAULT_FROM_EMAIL = 'hypnotherapyapplication@gmail.com'
DEFAULT_FROM_EMAIL = 'info.hypnosession@gmail.com'
EMAIL_PORT = 465
EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'hypnotherapyapplication@gmail.com'
EMAIL_HOST_USER = 'info.hypnosession@gmail.com'
# EMAIL_HOST_PASSWORD = 'hypnopass9'
EMAIL_HOST_PASSWORD = 'admin999hypno'
EMAIL_USE_SSL = True
# EMAIL_USE_TLS = True

# Settings for Rest Framework
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ]
}
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
USE_THOUSAND_SEPARATOR = True
# CURRENT_HOST
# CURRENT_HOST ='localhost:8000'
BASE_URL = 'http://101.50.1.185'

# Setting for message
RESET_PASSWORD_SUBJECT = '[NO REPLY] Konfirmasi Reset Password'
RESET_PASSWORD_MESSAGE = '''<p>Terima kasih telah menggunakan layanan ini.
            <br/>Layanan ini digunakan untuk me-reset password apabila pengguna lupa passwordnya.
            <br/>Berikut ini terdapat alamat url untuk melakukan reset password:<br/><p/>'''
ACCOUNT_VERIFICATION_SUBJECT = '[NO REPLY] Verifikasi Akun Pengguna'
ACCOUNT_VERIFICATION_MESSAGE = '''<p>Selamat Anda terlah terdaftar sebagai pengguna <strong>HypnoSession Mobile App</strong>.<br/>
                Selanjutnya, lakukan verifikasi pengguna dengan memasukkan kode sebagai berikut:<br/></p>'''
FORGET_PASSWORD_SUBJECT = '[NO REPLY] Kode Reset Password Pengguna'
FORGET_PASSWORD_MESSAGE = '''<p>Ini merupakan layanan untuk Reset Password. Selanjutnya, lakukan verifikasi pengguna 
                            <br/>dengan memasukkan kode sebagai berikut:<br/></p>'''
RESET_PASSWORD_MOBILE_SUBJECT ='[NO REPLY] Perubahan Password Pengguna'
RESET_PASSWORD_MOBILE_MESSAGE ='Proses perubahan Password yang Anda lakukan telah berhasil.'
