# Generated by Django 3.0.3 on 2020-03-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0003_auto_20200303_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='jenis_kelamin',
            field=models.BooleanField(),
        ),
    ]
