# Generated by Django 3.0.3 on 2020-03-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0004_auto_20200303_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akun',
            name='foto_path',
        ),
        migrations.AddField(
            model_name='akun',
            name='foto_src',
            field=models.TextField(null=True),
        ),
    ]
