# Generated by Django 3.0.3 on 2020-04-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0006_auto_20200314_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='verification_code',
            field=models.IntegerField(null=True),
        ),
    ]
