# Generated by Django 3.0.3 on 2020-04-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0007_akun_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
