# Generated by Django 3.0.3 on 2020-04-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0010_auto_20200426_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='nama',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
