# Generated by Django 3.0.3 on 2020-03-10 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0005_auto_20200310_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('konten', models.TextField()),
                ('aktif', models.BooleanField(default=True)),
                ('publikasi', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artikel',
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('konten', models.TextField(null=True)),
                ('publikasi', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('aktif', models.BooleanField(default=True)),
                ('artikel', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='artikel.Artikel')),
                ('member', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='akun.Akun')),
            ],
            options={
                'db_table': 'komentar',
            },
        ),
    ]
