# Generated by Django 3.0.3 on 2020-03-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
    ]
