# Generated by Django 3.0.3 on 2020-03-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_auto_20200310_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='aktif',
        ),
    ]
