# Generated by Django 3.0.3 on 2020-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_remove_komentar_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
