# Generated by Django 3.0.3 on 2020-03-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0006_auto_20200314_1358'),
        ('artikel', '0004_komentar_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='penulis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='artikel.Artikel'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='akun.Akun'),
        ),
    ]
