# Generated by Django 3.0.3 on 2020-03-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0006_auto_20200324_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='logo_src',
            new_name='ikon_src',
        ),
    ]
