# Generated by Django 3.0.3 on 2020-03-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0004_auto_20200303_0328'),
        ('hypno', '0004_auto_20200306_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.DateTimeField(auto_now_add=True)),
                ('bukti_path', models.TextField()),
                ('tanggal_bayar', models.DateTimeField()),
                ('rek_pemesan', models.CharField(max_length=100)),
                ('bank_pemesan', models.CharField(max_length=100)),
                ('an_pemesan', models.CharField(max_length=100)),
                ('rek_tujuan', models.CharField(max_length=100)),
                ('bank_tujuan', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField()),
                ('status', models.CharField(choices=[('konfirmasi', 'Konfirmasi'), ('pesan', 'Pesan'), ('aktif', 'Aktif')], default='pesan', max_length=12)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.Akun')),
                ('paket_terapi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypno.PaketTerapi')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
