# Generated by Django 3.0.3 on 2020-03-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hypno', '0008_auto_20200314_1721'),
        ('akun', '0006_auto_20200314_1358'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='akun.Akun'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paket_terapi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='hypno.PaketTerapi'),
        ),
    ]
